apiVersion: v1
kind: Secret
metadata:
  name: asumivillafuerte-api-secret
  namespace: asumivillafuerte-api-ns
  labels:
    app: asumivillafuerte-api

type: Opaque
data:
  username: c2E=
  password: cGFzc3dvcmQ=